type Shop {
  id: ID!
  name: String
  address: String
  deliveryEnabled: Boolean!
  services: [Service!]
  orders: [JSON!]
  position: Position
}
type Service {
  id: ID!
  name: String!
  price: Float!
}
type Query {
  shops: [Shop!]
  timestamp: String!
}
type Mutation {
  updateShop(shopId: String!, shopData: JSON!): [Shop!]
  removeShop(shopId: String!): [Shop!]
  timestamp: String!
}
